exclude             : [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]
safe                : true
lsi                 : false
pygments            : true

# Post configs
paginate            : 5
paginate_path       : "blog/page:num"
permalink           : /blog/:categories/:year/:month/:day/:title.html

# Site's URL
url                 : http://trananh.github.io

# Disqus configs
comments            : false
disqus_shortname    : 'trananh'
