exclude         : [".ruby-version"]
safe            : true
lsi             : false
pygments        : true

paginate        : 5
paginate_path   : "blog/page:num"

url             : http://trananh.io.github