exclude             : [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]
safe                : true
lsi                 : false
pygments            : true

paginate            : 5
paginate_path       : "blog/page:num"

url                 : http://trananh.github.io

# Disqus configs
comments            : false
disqus_shortname    : 'trananh'

# sitemap configs
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/blog/atom.xml"
    include_posts:
        - "/blog/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
