exclude         : [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]
safe            : true
lsi             : false
pygments        : true

paginate        : 5
paginate_path   : "blog/page:num"

url             : http://trananh.github.io